apiVersion: v1
kind: Service
metadata:
  name: intellifleet-ui-service
spec:
  selector:
    app: intellifleet-ui-app
  type: NodePort
  ports:
    - name: app-port
      port: 80
      targetPort: 80
      nodePort: 30083 