import DynamicForm from "@mui/icons-material/DynamicForm";

const OBJECTS = {
    DASHBOARD: "dashboard",
    USER_DETAILS: "user-details",
    SETTINGS: "settings",
    USER_PROFILE: "user-profile",
    ENTITY_DETAILS: "entity-details",
    USER_ROLE_PERMISSION: "user-role-permission",
    NOTES: "notes",
    MY_DETAILS: "my-details",
    ORG_DETAILS: "org-details",
//===================================================================
    //UI : This two chars used as object prefix because this objects are used only for Rect UI manipulation
    CLIENT_GROUP: "client-group",
    CLIENT_GROUP_CHILD: "client-group-child",
    CUSTOMER: "customer",
    TRIP_UPLOAD: "trip-upload",
    TRIP_DETAILS: "trip-details",

    MENU_GOOGLE_MAP: "menu-google-map",
    MAP_ASSET_POSITION: "asset-position",
    MAP_ASSET_TRIP_ANALYSIS: "asset-trip-analysis",
    MAP_GEO_FENCE: "geo-fence",

    FORM: "form",
    UI_FORM_BUILDER: "ui-form-builder",
    UI_FORM_GENERATOR: "ui-form-generator",
    UI_QUERY: "ui-query",
    UI_TRIP: "ui-menu-trip",
}

const OBJECTS_LABEL = {}
OBJECTS_LABEL[OBJECTS.DASHBOARD] = "Dashboard";
OBJECTS_LABEL[OBJECTS.USER_DETAILS] = "User Details";
OBJECTS_LABEL[OBJECTS.SETTINGS] = "Settings";
OBJECTS_LABEL[OBJECTS.USER_PROFILE] = "User Profile";
OBJECTS_LABEL[OBJECTS.ENTITY_DETAILS] = "Entity Details";
OBJECTS_LABEL[OBJECTS.USER_ROLE_PERMISSION] = "User Role Permission";
OBJECTS_LABEL[OBJECTS.NOTES] = "Notes";
OBJECTS_LABEL[OBJECTS.MY_DETAILS] = "My Details";
OBJECTS_LABEL[OBJECTS.ORG_DETAILS] = "Organisation Details";

OBJECTS_LABEL[OBJECTS.CLIENT_GROUP] = "Client Group";
OBJECTS_LABEL[OBJECTS.CLIENT_GROUP_CHILD] = "Client Group Child";
OBJECTS_LABEL[OBJECTS.CUSTOMER] = "Customer";
OBJECTS_LABEL[OBJECTS.UI_TRIP] = "Trip";
OBJECTS_LABEL[OBJECTS.TRIP_UPLOAD] = "Generic Trip Upload";
OBJECTS_LABEL[OBJECTS.TRIP_DETAILS] = "Trip Details";

OBJECTS_LABEL[OBJECTS.MENU_GOOGLE_MAP] = "Google Map";
OBJECTS_LABEL[OBJECTS.MAP_ASSET_POSITION] = "Asset Position";
OBJECTS_LABEL[OBJECTS.MAP_ASSET_TRIP_ANALYSIS] = "Asset Trip Analysis";
OBJECTS_LABEL[OBJECTS.MAP_GEO_FENCE] = "Geo Fence";

OBJECTS_LABEL[OBJECTS.FORM] = "Form";
OBJECTS_LABEL[OBJECTS.UI_FORM_BUILDER] = "Form Builder";
OBJECTS_LABEL[OBJECTS.UI_FORM_GENERATOR] = "Form Generator";
OBJECTS_LABEL[OBJECTS.UI_QUERY] = "Query";


const ICONS = {
}
ICONS[OBJECTS.DASHBOARD] = <i style={{marginLeft: 6, marginTop: 6,}} className="fa fa-th-large" aria-hidden="true"></i>;
ICONS[OBJECTS.CLIENT_GROUP] = <i style={{marginLeft: 6, }} className="fa fa-users" aria-hidden="true"></i>;
ICONS[OBJECTS.CLIENT_GROUP_CHILD] = <i style={{marginLeft: 6,}} className="fa fa-database" aria-hidden="true"></i>;
ICONS[OBJECTS.CUSTOMER] = <i style={{marginLeft: 6, fontSize: 13}} className="fa fa-industry" aria-hidden="true"></i>;
ICONS[OBJECTS.USER_DETAILS] = <i style={{marginLeft: 6, marginTop: 6,}} className="fa fa-user-o" aria-hidden="true"></i>;
ICONS[OBJECTS.SETTINGS] = <i style={{marginLeft: 6, marginTop: 6,}} className="fa fa-gear" aria-hidden="true"></i>;
ICONS[OBJECTS.NOTES] = <i style={{marginLeft: 6, marginTop: 6,}} className="fa fa-book" aria-hidden="true"></i>;
ICONS[OBJECTS.MY_DETAILS] = <i style={{marginLeft: 6, marginTop: 6,}} className="fa fa-book" aria-hidden="true"></i>;
ICONS[OBJECTS.ORG_DETAILS] = <i style={{marginLeft: 6, marginTop: 6,}} className="fa fa-book" aria-hidden="true"></i>;

ICONS[OBJECTS.FORM] = <DynamicForm fontSize={'inherit'} style={{fontSize: 16, margin: 5}}/>;
ICONS[OBJECTS.UI_QUERY] = <i style={{marginLeft: 6, fontSize: 13}} className="fa fa-quora" aria-hidden="true"></i>;


const USER_ROLE = {
    SADMIN: "SADMIN",
    USER: "USER",
    ADMIN: "ADMIN",
    FOUNDER: "FOUNDER",
    CEO: "CEO",
    GENERAL_MANAGER: "GENERAL-MANAGER",
    BRANCH_HEAD: "BRANCH-HEAD",
    HEAD_OF_OPERATION_AND_LOGISTICS: "HEAD-OF-OPERATION-AND-LOGISTICS",
    OPERATION_MANAGER: "OPERATION-MANAGER",
    ASSISTANT_OPERATION_MANAGER: "ASSISTANT-OPERATION-MANAGER",
    BUSINESS_DEVELOPER_AND_PROJECT_MANAGER: "BUSINESS-DEVELOPER-AND-CUSTOMER-MANAGER",
    FLOOR_MANAGER: "FLOOR-MANAGER",
    ASSISTANT_FLOOR_MANAGER: "ASSISTANT-FLOOR-MANAGER",
    SUPERVISOR: "SUPERVISOR",
    ASSISTANT_SUPERVISOR: "ASSISTANT-SUPERVISOR",
    SOFTWARE_DEVELOPER: "SOFTWARE-DEVELOPER",
    QC_HEAD: "QC-HEAD",
    SENIOR_QC: "SENIOR-QC",
    INTERMEDIATE_QC: "INTERMEDIATE-QC",
    QC: "QC",
    SENIOR_DATA_ANALYST: "SENIOR-DATA-ANALYST",
    INTERMEDIATE_DATA_ANALYST: "INTERMEDIATE-DATA-ANALYST",
    DATA_ANALYST: "DATA-ANALYST",
    TRANSPORTATION_STAFF: "TRANSPORTATION-STAFF",
    MAINTENANCE_STAFF: "MAINTENANCE-STAFF"
}

const USER_PERMISSION = {
    ADD: "ADD",
	VIEW: "VIEW",
	EDIT: "EDIT",
	DELETE: "DELETE",
    CHILD_VIEW: "CHILD-VIEW",
}

const AVAILABLE_CRUD_OPERATIONS = {};
AVAILABLE_CRUD_OPERATIONS[OBJECTS.ORG_DETAILS] = [USER_PERMISSION.ADD,USER_PERMISSION.VIEW, USER_PERMISSION.EDIT];
AVAILABLE_CRUD_OPERATIONS[OBJECTS.BANK_DETAILS] = [USER_PERMISSION.ADD,USER_PERMISSION.VIEW, USER_PERMISSION.CHILD_VIEW, USER_PERMISSION.EDIT,USER_PERMISSION.DELETE];
AVAILABLE_CRUD_OPERATIONS[OBJECTS.DASHBOARD] = [USER_PERMISSION.ADD,USER_PERMISSION.VIEW,USER_PERMISSION.EDIT,USER_PERMISSION.DELETE];
AVAILABLE_CRUD_OPERATIONS[OBJECTS.ENTITY_DETAILS] = [USER_PERMISSION.ADD,USER_PERMISSION.VIEW,USER_PERMISSION.EDIT,USER_PERMISSION.DELETE];
AVAILABLE_CRUD_OPERATIONS[OBJECTS.SETTINGS] = [USER_PERMISSION.VIEW];
AVAILABLE_CRUD_OPERATIONS[OBJECTS.USER_DETAILS] = [USER_PERMISSION.ADD,USER_PERMISSION.VIEW,USER_PERMISSION.EDIT,USER_PERMISSION.DELETE];
AVAILABLE_CRUD_OPERATIONS[OBJECTS.USER_ROLE_PERMISSION] = [USER_PERMISSION.EDIT,USER_PERMISSION.VIEW];
AVAILABLE_CRUD_OPERATIONS[OBJECTS.USER_PROFILE] = [USER_PERMISSION.ADD,USER_PERMISSION.VIEW,USER_PERMISSION.EDIT];
AVAILABLE_CRUD_OPERATIONS[OBJECTS.NOTES] = [USER_PERMISSION.ADD,USER_PERMISSION.CHILD_VIEW];
AVAILABLE_CRUD_OPERATIONS[OBJECTS.MY_DETAILS] = [USER_PERMISSION.VIEW];
AVAILABLE_CRUD_OPERATIONS[OBJECTS.ORG_DETAILS] = [USER_PERMISSION.ADD,USER_PERMISSION.VIEW,USER_PERMISSION.EDIT,USER_PERMISSION.DELETE];

const OBJECT_PARENT_CHILD_MAPPING = {};
OBJECT_PARENT_CHILD_MAPPING[OBJECTS.EMPLOYEE_DETAILS] = [
    OBJECTS.NOTES,
    OBJECTS.DOCUMENTS,
    OBJECTS.BANK_DETAILS,
    OBJECTS.EMPLOYEE_MONTHLY_PAYABLE_SALARY,
    OBJECTS.EMP_MACHINE_DETAILS,
    OBJECTS.M_DESIGNATED_HOLIDAYS,
    OBJECTS.EMPLOYEE_LEAVES
];

OBJECT_PARENT_CHILD_MAPPING[OBJECTS.EMPLOYEE_LEAVES] = [
    OBJECTS.NOTES,
    OBJECTS.EMPLOYEE_LEAVES_DETAILS,
]; 

OBJECT_PARENT_CHILD_MAPPING[OBJECTS.EMPLOYEE_SALARY] = [
    OBJECTS.EMPLOYEE_SALARY_DETAILS,
]; 

OBJECT_PARENT_CHILD_MAPPING[OBJECTS.EMPLOYEE_MONTHLY_PAYABLE_SALARY] = [
    OBJECTS.EMPLOYEE_MONTHLY_PAYABLE_SALARY_DETAILS,
]; 

OBJECT_PARENT_CHILD_MAPPING[OBJECTS.BANK_DETAILS] = [
    OBJECTS.EMPLOYEE_DETAILS,
]

OBJECT_PARENT_CHILD_MAPPING[OBJECTS.DOCUMENTS] = [
]

OBJECT_PARENT_CHILD_MAPPING[OBJECTS.USER_DETAILS] = [
    OBJECTS.EMPLOYEE_DETAILS,
]

const STATUS = {}
STATUS[OBJECTS.EMPLOYEE_LEAVES] = {
    PENDING : "PENDING",
    APPROVED : "APPROVED",
    DECLINED : "DECLINED"
}

const STATUS_COLOR = {}
STATUS_COLOR[STATUS[OBJECTS.EMPLOYEE_LEAVES].PENDING] = "yellowgreen";
STATUS_COLOR[STATUS[OBJECTS.EMPLOYEE_LEAVES].APPROVED] = "green";
STATUS_COLOR[STATUS[OBJECTS.EMPLOYEE_LEAVES].DECLINED] = "red";

const BROWSER_SUPPORTED_FILE_TYPES = [
    'PDF',
    'JPG',
    'JPEG',
    'PNG',
    'GIF',
    'BMP',
    'SVG',
    'TXT',
    'HTML',
    'CSS',
    'JS'
  ];
  

const CONSTANSTS = {
    OBJECTS: OBJECTS,
    OBJECTS_LABEL: OBJECTS_LABEL,
    ICONS: ICONS,
    USER_ROLE: USER_ROLE,
    USER_PERMISSION: USER_PERMISSION,
    AVAILABLE_CRUD_OPERATIONS: AVAILABLE_CRUD_OPERATIONS,
    OBJECT_PARENT_CHILD_MAPPING: OBJECT_PARENT_CHILD_MAPPING,
    STATUS: STATUS,
    STATUS_COLOR: STATUS_COLOR,
    BROWSER_SUPPORTED_FILE_TYPES: BROWSER_SUPPORTED_FILE_TYPES
}

export default CONSTANSTS;