pipeline {
    agent any

    environment {
        // PATH = '/opt/intellifleet/software/nodejs/24/bin:$PATH'
        REPO_URL = 'https://github.com/intfleet/intellifleet-ui'
        BRANCH = 'feature/dev-01'

        IMAGE_NAME = "intellifleet-ui-image"
        IMAGE_TAG = "${BUILD_NUMBER}"
        TAR_FILE = "intellifleet-ui-image.tar"
        DEPLOYMENT_NAME = "intellifleet-ui-app"
    }

    stages {

        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout') {
            steps {
                git branch: "${BRANCH}", url: "${REPO_URL}"
            }
        }

        stage('Build React App') { 
            steps { 
                sh ''' 
                docker run --rm \
                -v $WORKSPACE:/app \
                -w /app \
                node:20 \
                sh -c "npm install --legacy-peer-deps && npm run build" 
                ''' 
            } 
        }

        

        stage('Build Docker Image') {
            steps {
                sh '''
                echo "Build Docker Image"
                docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
                docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
                '''
            }
        }

        stage('Save Docker Image') {
            steps {
                sh '''
                echo "Save Docker Image"
                docker save $IMAGE_NAME:latest -o k8s/${TAR_FILE}
                ls -l k8s/${TAR_FILE}
                '''
            }
        }

        stage('Import to containerd') {
            steps {
                sh '''
                echo "Import Docker Image to containerd"
                ctr -n k8s.io images import k8s/${TAR_FILE}
                '''
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f k8s/deployment.yaml'
                sh 'kubectl apply -f k8s/service.yaml'
            }
        }

        stage('Restart Deployment') {
            steps {
                sh 'kubectl rollout restart deployment/${DEPLOYMENT_NAME}'
            }
        }

        stage('Verify Rollout') {
            steps {
                sh 'kubectl rollout status deployment/${DEPLOYMENT_NAME}'
            }
        }
    }

    post {
        success {
            echo 'Deployment successful ✅'
        }
        failure {
            echo 'Deployment failed ❌'
        }
    }
}