pipeline {
    agent any

    environment {
        PATH = '/root/.nvm/versions/node/v16.20.2/bin:/usr/local/bin:/usr/bin:/bin:${env.PATH}'
        REPO_URL = 'https://github.com/intfleet/intellifleet-ui'
        BRANCH = 'feature/dev-01'

        IMAGE_NAME = "intellifleet-ui-image"
        IMAGE_TAG = "${BUILD_NUMBER}"
        TAR_FILE = "intellifleet-ui-image.tar"
        DEPLOYMENT_NAME = "intellifleet-ui-app"
    }

    stages {

        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout') {
            steps {
                git branch: "${BRANCH}", url: "${REPO_URL}"
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Build React App') {
            steps {
                sh 'npm run build'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .'
            }
        }

        stage('Save Docker Image') {
            steps {
                sh 'docker save ${IMAGE_NAME}:${IMAGE_TAG} -o k8s/${TAR_FILE}'
            }
        }

        stage('Import to containerd') {
            steps {
                sh 'ctr -n k8s.io images import k8s/${TAR_FILE}'
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f k8s/deployment.yaml'
                sh 'kubectl apply -f k8s/service.yaml'
            }
        }

        stage('Restart Deployment') {
            steps {
                sh 'kubectl rollout restart deployment/${DEPLOYMENT_NAME}'
            }
        }

        stage('Verify Rollout') {
            steps {
                sh 'kubectl rollout status deployment/${DEPLOYMENT_NAME}'
            }
        }
    }

    post {
        success {
            echo 'Deployment successful ✅'
        }
        failure {
            echo 'Deployment failed ❌'
        }
    }
}